server.port: 8088

logging:
  level:
    ru.journal: DEBUG
  file:
    name: ./logs/journal.log
    path: logs

spring:
  application:
    name: Exchange rate Journal
  profiles:
    active: dev
  liquibase:
    change-log: db/changelog/changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/Journal
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate.ddl-auto: validate
  properties:
    hibernate:
      jdbc:
        batch_size: 43

api-url:
  cbr-daily: https://www.cbr-xml-daily.ru/daily_utf8.xml

scheduled-rate: PT1H